version: "3.8"

services:
  backend:
    build: "./backend-stt"
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend-stt:/usr/src
      - /usr/src/node_modules
    command: npx nodemon -L index.js

  # front:
  #   build: "./technical-test-stt"
  #   environment:
  #     BACK_URL: "mongodb://backend:3000"
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./technical-test-stt:/usr/src
  #     - /usr/src/node_modules
  #   command: npm run dev -- --host

  db:
    image: mongo